#!/usr/bin/bash

_refresh(){
  sh -c "${*#$1}; echo '[refresh] Refreshed $1'" & disown
}

_refresh "Fonts" fc-cache
_refresh "Tint2" tint2ctl refresh
_refresh "Openbox" openbox --reconfigure
_refresh "Xresources" xrdb ~/.Xresources

_refresh "Compositor" 'toggle_compositor refresh &> /dev/null'
_refresh "xsettingsd" 'killall -HUP xsettingsd &> /dev/null'

sleep 3

if [ -z "$1" ]; then
  notify-send -u low -t 700 -i preferences-color "Refreshed"
fi

exit 0
