#!/usr/bin/env sh

# Quick Refresh Everything

# Refresh Fonts
fc-cache &

# Refresh Termite
killall -USR1 termite &

# Refresh Tint2
killall -SIGUSR1 tint2 &

# Refresh Picom
(
killall -w picom && picom -b &> /dev/null
) &

# Refresh Window Manager
openbox --reconfigure &

# Refresh xsettingsd / GTK
(
killall -HUP xsettingsd || xsettingsd &> /dev/null
) &

# Notify Users
notify-send -u low -t 800 -i $(icon_path -s , preferences-color) "Refresh" &> /dev/null
