#!/usr/bin/env sh

_refresh(){
  sh -c "${*#$1}; echo '[refresh] Refreshed $1'" & disown
}

_refresh "Fonts" fc-cache
_refresh "Tint2" tint2ctl refresh
_refresh "Openbox" openbox --reconfigure
_refresh "Xresources" xrdb ~/.Xresources

_refresh "Picom" '(killall -w picom && picom -b &) &> /dev/null'
_refresh "xsettingsd" '(killall -HUP xsettingsd || xsettingsd &) &> /dev/null'

sleep 1

[[ -z $1 ]] && \
  notify-send -u low -t 700 -i $(icon_path -s , preferences-color) \
   "Refreshed" &> /dev/null

exit 0