#!/usr/bin/sh

# Search for a Xorg Display
test -z $DISPLAY && echo "Couldn't find a Display." && exit 1

# comp_cmd='xcompmgr -cCfF -o.80 -r11 -t-13 -l-13 -D2'
comp_cmd='picom -cf -o.80 -r11 -t-9 -l-9 -D2 -i.95 -e.85'
was_open=''

if killall -w ${comp_cmd%% *} &> /dev/null; then
  echo "Killed Compositor."
  was_open='true'
fi

if [[ $1 == refresh ]]; then
  if [[ -z $was_open ]]; # Invert
    then was_open='true'
    else was_open=''
  fi
fi


if [[ $1 != off && ($1 == on || -z $was_open) ]];
  then echo "Compositor will start."; $comp_cmd & disown
  else echo "Compositor remains killed."
fi

